### ISSUE TITLE
[Q] Unable to change FreeRTOSConfig.h for a single sketch on Arduino IDE 2.2.1

### ISSUE THREAD

**Issue by daitangio** [feilipu/Arduino_FreeRTOS_Library#125]
Hi, first of all thank you for porting FreeRTOS to Arduino R4 too!

I am using Arduino IDE 2.x and I seems unable to change the option
`#define INCLUDE_uxTaskGetStackHighWaterMark (1)`
If I create a 
` FreeRTOSConfig.h`
inside my sketch, include it  before Arduino_FreeRTOS.h  but it seems ignored.
The only way to get it wortking is to edit the FreeRTOSConfig.h inside the library, which seems quite ugly.
Do you have some suggestions to be able to get it on per-sketch basis?
Thank you!

**Comment by feilipu** [comment]
Sorry for the delay. I've been AFK for a (long) time.

No. There is no better way to fix this. AFAIK, the library version of `FreeRTOSConfig.h` will always win because it is referenced when the library is compiled. Just an issue with Arduino IDE and its desire to keep everything simple for users. So, just modify it as per your need.
