### ISSUE TITLE
FreeRTOS Updates are strange...

### ISSUE THREAD

**Issue by SalvorinFex** [feilipu/Arduino_FreeRTOS_Library#8]
I have been trying to keep up to date on these releases but something is acting against me.

When I try to update it keeps installing 8.2.3, instead of 8.2.3-xx.
This screenshot shows what it looks like:
[(https://www.dropbox.com/s/gh2h3q2yxs7nen5/Screenshot%202016-09-19%2014.52.06.png?dl=0)]

I try to catch it when I perform updates to the rest of the libraries and skip that one, but I miss it sometimes.

This happens on at least 3 separate windows systems.

**Comment by feilipu** [comment]
Yes this is related to two issues with the Arduino IDE.

As background, see the [Library Manager FAQ](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ).

1. Deleting old releases.
"In order to unpublish a library version, delete its related tag/release. Deleted library versions are removed from the list every Sunday."

This doesn't seem to work. It won't forget old releases, event though the release is deleted on GitHub as instructed.

2. SemVer Versioning.
Arduino IDE follows the [SemVer](http://semver.org/) format for versions. Once you release a root numbered release (eg 8.2.3) this is seen as the "final" release. And any dash releases (eg 8.2.3-xx) are seen as preliminary or beta releases.

"When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version."

As I'm releasing implementations of the same FreeRTOS code (8.2.3), it doesn't make sense to increment the patch number.

Therefore. -> Unfortunately through these two issues the root version (no dash number) that was my first (quite buggy) release, is therefore captured in perpetuity as the "latest" release.
